export const timeZones = [
  {label: "GMT-12", value: "GMT-12"},
  {label: "GMT-11", value: "GMT-11"},
  {label: "GMT-10", value: "GMT-10"},
  {label: "GMT-09", value: "GMT-09"},
  {label: "GMT-08", value: "GMT-08"},
  {label: "GMT-07", value: "GMT-07"},
  {label: "GMT-06", value: "GMT-06"},
  {label: "GMT-05", value: "GMT-05"},
  {label: "GMT-04", value: "GMT-04"},
  {label: "GMT-03", value: "GMT-03"},
  {label: "GMT-02", value: "GMT-02"},
  {label: "GMT-01", value: "GMT-01"},
  {label: "GMT", value: "GMT"},
  {label: "GMT+01", value: "GMT+01"},
  {label: "GMT+02", value: "GMT+02"},
  {label: "GMT+03", value: "GMT+03"},
  {label: "GMT+04", value: "GMT+04"},
  {label: "GMT+05", value: "GMT+05"},
  {label: "GMT+06", value: "GMT+06"},
  {label: "GMT+07", value: "GMT+07"},
  {label: "GMT+08", value: "GMT+08"},
  {label: "GMT+09", value: "GMT+09"},
  {label: "GMT+10", value: "GMT+10"},
  {label: "GMT+11", value: "GMT+11"},
  {label: "GMT+12", value: "GMT+12"},
];